// Tests the distribution generated by Java's Math.random() function.

import java.util.Random;

public  class  TestRandom {
	public static void main(String[]  args) {
		int times = Integer.parseInt(args[0]);
		int sCount = 0; 
		int lCount = 0;
		double random;
		for (int i = times; i > 0; i--) {
			random = Math.random();
			if (random > 0.5) {
				lCount ++;
			}
			else {
				sCount ++;
			}
		}

		if (sCount == 0){
			System.out.println((String)"There are no numbers below 0.5");
		}
		else if (lCount == 0){
			System.out.println((String) "There are no numbers above 0.5");
		}

		else  {
			double Ratio = (float) lCount / sCount;
			System.out.println(Ratio);
		}
		// System.out.println(times + "," + sCount + "," + lCount);
		// java TestRandom.java 100
		// java TestRandom.java 3

	}
}
