// Tests the distribution generated by Java's Math.random() function.

import java.util.Random;

public  class  TestRandom {
	public static void main(String[]  args) {
		int times = Integer.parseInt(args[0]);
		int sCount = 0; 
		int lCount = 0;
		double random;
		for (int i = times; i > 0; i--) {
			random = Math.random();
			if (random > 0.5) {
				lCount ++;
			}
			else {
				sCount ++;
			}
		}
		 double Ratio = (float) lCount / sCount;

		// System.out.println(times + "," + sCount + "," + lCount);
		System.out.println(Ratio);

		// java TestRandom.java 100

	}
}
